#!/bin/bash

RELEASE_DIR="build/Release"

mkdir -p $RELEASE_DIR
cmake -B $RELEASE_DIR -DCMAKE_BUILD_TYPE=Release
cmake --build $RELEASE_DIR -j 6 || { echo -e "\n[Error] Build failed"; exit 1; }

if [ ! -n "$1" ]; then
    echo "Usage: $0 <dataset_name> [model_name] [grid_file]"
    exit 1
fi

# --------------------
# Training parameters

EPOCHS=500
PATIENCE=50
INNER_K=1
OUTER_K=1

DATASET_RATIO=1.0
TRAIN_RATIO=0.8

# --------------------

NAME="$1"
if [ -n "$2" ]; then
    NAME="$2"
fi

if [ -n "$3" ]; then
    GRID_FILE="grids/$3.csv"
else
    GRID_FILE="grids/$1.csv"
fi

if [ ! -f "$GRID_FILE" ]; then
    echo "[Error] Grid file not found: $GRID_FILE"
    exit 1
fi

LAUNCHER=""
if command -v booster >/dev/null 2>&1; then
    LAUNCHER="booster"
fi

clear
echo "[1] Early Stop"
echo "[2] Live Plot"
echo "[3] Best Model"
echo "[4] Kill Process"

$LAUNCHER ./$RELEASE_DIR/NeuralNet "$1" --name "$NAME" \
    --params $GRID_FILE --train --shuffle \
    --dataset_ratio $DATASET_RATIO --train_ratio $TRAIN_RATIO \
    --inner-k $INNER_K --outer-k $OUTER_K --epochs $EPOCHS --patience $PATIENCE &


NN_PATTERN="NeuralNet $1 --name $NAME --params"
NN_PID=""
# Wait for the NeuralNet process to start and get its PID
for _ in $(seq 1 100); do
    for pid in $(pgrep -f -- "$NN_PATTERN"); do
        if [ "$(<"/proc/$pid/comm")" = "NeuralNet" ]; then
            NN_PID="$pid"
            break 2
        fi
    done
    sleep 0.1
done

if [ -z "$NN_PID" ]; then
    echo "[Error] Could not find the NeuralNet process"
    exit 1
fi

run_live_plot() {
    python3 ./scripts/live_plot.py "$NAME" >/dev/null 2>&1 &
}

run_best_model() {
    python3 ./scripts/best_model.py "$NAME" >/dev/null 2>&1 &
}

run_live_plot

while true; do
    if read -t 1 -n 1 -s key; then
        if ! kill -0 "$NN_PID" 2>/dev/null; then
            break
        fi

        if [[ $key == "1" ]]; then
            kill -SIGUSR1 "$NN_PID"
        elif [[ $key == "2" ]]; then
            run_live_plot
        elif [[ $key == "3" ]]; then
            run_best_model
        elif [[ $key == "4" ]]; then
            kill -SIGINT "$NN_PID"
        fi
    fi
    if ! kill -0 "$NN_PID" 2>/dev/null; then
        break
    fi
done

run_best_model