#!/bin/bash

RELEASE_DIR="build/Release"

mkdir -p $RELEASE_DIR
cmake -B $RELEASE_DIR -DCMAKE_BUILD_TYPE=Release
cmake --build $RELEASE_DIR -j 6 || { echo -e "\n[Error] Build failed"; exit 1; }

if [ ! -n "$1" ]; then
    echo "Usage: $0 <dataset_name> [model_name] [grid_file]"
    exit 1
fi

# --------------------
# Training parameters

EPOCHS=1000
PATIENCE=60
INNER_K=1
OUTER_K=1

DATASET_RATIO=1.0
TRAIN_RATIO=0.8

# --------------------

NAME="$1"
if [ -n "$2" ]; then
    NAME="$2"
fi

GRID_FILE="grids/grid.csv"
if [ -n "$3" ]; then
    GRID_FILE="grids/$3.csv"
fi

clear
echo "[1] Early Stop"
echo "[2] Live Plot"
echo "[3] Best Model"
echo "[4] Kill Process"

booster ./$RELEASE_DIR/NeuralNet "$1" --name "$NAME" --train --shuffle \
    --params $GRID_FILE \
    --dataset_ratio $DATASET_RATIO --train_ratio $TRAIN_RATIO \
    --inner-k $INNER_K --outer-k $OUTER_K --epochs $EPOCHS --patience $PATIENCE &

live_plot=$(python3 ./scripts/live_plot.py "$NAME" >/dev/null 2>&1 &)
best_model=$(python3 ./scripts/best_model.py "$NAME" >/dev/null 2>&1 &)

$live_plot

while true; do
    if read -t 1 -n 1 -s key; then
        PID=$(pgrep "NeuralNet" | head -n 1)
        if [ -z "$PID" ]; then
            break
        fi

        if [[ $key == "1" ]]; then
            kill -SIGUSR1 "$PID"
        elif [[ $key == "2" ]]; then
            $live_plot
        elif [[ $key == "3" ]]; then
            $best_model
        elif [[ $key == "4" ]]; then
            kill -SIGINT "$PID"
        fi
    fi
    if ! pgrep "NeuralNet" > /dev/null; then
        break
    fi
done

$best_model